keys:
   key:
         account.manager.service: j98Nbf765bdiwD5ngks829450ykh287f7vydhGDS1

authorities:
    applications:
         -
          name: "client.node"
          authorities:
                - "create:account"
                - "read:account"
                - "update:account"
                - "delete:account"